version: "3.8"

services:
  routable-ml-fastapi:
    container_name: routable-ml-fastapi
    build: .
    command:  uvicorn main:app --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    user:
      "root"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]